# Generated by Django 4.1.6 on 2023-02-20 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landlord', '0009_remove_propertyinspection_property_id_and_more'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedproperty',
            unique_together={('property', 'tenant')},
        ),
    ]
