# Generated by Django 4.1.6 on 2023-02-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0006_property_furnished'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='airConditioning',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='gym',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='pool',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
