# Generated by Django 4.1.6 on 2023-02-20 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinspection',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
