# Generated by Django 4.1.6 on 2023-02-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0003_profile_image_profile_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.CharField(default='', max_length=100),
        ),
    ]
