# Generated by Django 4.1.6 on 2023-02-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0004_property_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='room',
            field=models.IntegerField(default=0),
        ),
    ]
