# Generated by Django 4.1.6 on 2023-02-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0005_remove_property_features_property_bathroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.CharField(default='', max_length=30),
        ),
    ]
