# Generated by Django 4.1.6 on 2023-02-28 10:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0002_alter_property_image_alter_property_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('cover_letter', models.TextField(blank=True, max_length=500)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='files/income/')),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='files/identity/')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='files/income/')),
            ],
        ),
        migrations.CreateModel(
            name='Residential',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='files/residential/')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationResidential',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.residential')),
            ],
            options={
                'unique_together': {('application', 'residential')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationIncome',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.income')),
            ],
            options={
                'unique_together': {('application', 'income')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationIdentity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.income')),
            ],
            options={
                'unique_together': {('application', 'income')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationEmployment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.employment')),
            ],
            options={
                'unique_together': {('application', 'employment')},
            },
        ),
    ]
