# Generated by Django 4.1.6 on 2023-02-28 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationidentity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='applicationidentity',
            name='identity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.identity'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='applicationidentity',
            unique_together={('application', 'identity')},
        ),
        migrations.RemoveField(
            model_name='applicationidentity',
            name='income',
        ),
    ]
