# Generated by Django 4.1.6 on 2023-02-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_applicationidentity_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='file',
            field=models.FileField(blank=True, upload_to='files/identity/'),
        ),
    ]
